name: automl
dependencies:
  - python==3.7.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  - scikit-learn==0.20.1
  - statsmodels==0.9.0
  - xgboost
  - pandas-profiling # EDA
  - spyder-kernels==2.0.1
  - pip
  - pip:
    - xlrd==1.2.0 # pd.read_excel
    - PyYAML # yml files
    - dataprep # data preparation with good EDA
    - missingno # missing values
    #- hiplot # parallel plot
    - featexp # features analysis
    #- visions # data summarization for any type of data
    - mljar-supervised # automated ml 
    - tpot # automated ml
    - hyperopt # Bayesian optimization of parameters
 
## Installing auto-sklearn (no hay manera en MacOS)
#curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip3 install
#pip install auto-sklearn

## Installing hyperopt-sklearn
# https://github.com/hyperopt/hyperopt-sklearn
#pip install git+https://github.com/hyperopt/hyperopt-sklearn
