name: crawling
dependencies:
  - python==3.7.0
  - jupyter
  #- jupyterlab==1.1.4
  - scipy==1.1.0
  - pandas==0.23.4
  - numpy==1.15.1
  - click
  #- scrapy==1.6
  - beautifulsoup4
  - requests
  #- spyder-kernels
  - pip:
    - PyYAML 
