name: mltools
dependencies:
  - python==3.6.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  - scikit-learn==0.20.1
  - statsmodels==0.9.0
  - click
  - pip:
    #- mlflow==0.5.2
    #- xgboost==0.80
    #- pygam==0.7.1
    #- hyperopt
    #- hpsklearn
    - featexp # features analysis
    #- dtw # DTW (Dynamic Time Warping)
    #- fastdtw # fast DTW (Dynamic Time Warping)
    - plotly 
