name: geotool
dependencies:
  - python==3.7.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  - click
  #- spyder-kernels
  - pip:
    - haversine
    - geopandas
    - descartes
    - fiona  # select shapefile rows
    - geofeather # feather format for more quicker access.
