name: analysis
dependencies:
  - python==3.7.0
  - jupyter
  #- click # customized prints
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  - scikit-learn==0.20.1
  - statsmodels==0.9.0
  - pandas-profiling # EDA
  - spyder-kernels==2.0.1
  - pip
  - pip:
    - xlrd==1.2.0 # pd.read_excel
    - PyYAML # yml files
    - dataprep # data preparation with good EDA
    - missingno # missing values
    - hiplot # parallel plot
    - dataprep # EDA
    - featexp # features analysis
    - xgboost==0.80
    #- icecream # print with marks
    #- visions # data summarization for any type of data
